# Numpy
## Numpy란?
### numerical python 

파이썬에서 복잡한 수치계산도 효율적으로 동작 가능하도록 만든 프로그램
대용량의 수치 데이터를 Numpy array 형태로 간편하고 효율적으로 저장하고 사용할 수 있음.

## numpy array의 생김새 


In [2]:
import numpy

In [2]:
array1 = numpy.array([2,3,4,7,11,13,17,19,23,29,31])
    # numpy 모듈의 array함수에 파이썬 리스트를 파라미터로 사용하여 numpy array를 만듬

In [3]:
array1

array([ 2,  3,  4,  7, 11, 13, 17, 19, 23, 29, 31])

**ndarray**  
n dimensional array. n차원의 배열. array는 다차원으로 배열을 만들 수 있다. 

* numpy arrary의 차원

In [4]:
type(array1)

numpy.ndarray

* 1차원

In [5]:
array1.shape

(11,)

* 2차원

In [8]:
array2 = numpy.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [9]:
type(array2)

numpy.ndarray

In [11]:
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

array안에 array가 있는 2차원 배열이다.  
shape 출력 시 세로 가로 길이가 나온다. 

In [10]:
array2.shape

(3, 4)

* 3차원  
크기를 나타낼 때는 가장 바깥쪽 리스트의 길이부터 가장 안쪽 리스트 길이의 순서로 표시한다. 

In [3]:
array3 = numpy.array([[[1, 2, 3, 4],
                       [5, 6, 7, 8],
                       [9, 10, 11, 12]],
                      [[11, 12, 13, 14],
                       [15, 16, 17, 18],
                       [19, 20, 21, 22]]])   # 2 x 3 x 4 array

In [4]:
array3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [8]:
array3.shape

(2, 3, 4)

In [6]:
# 3차원 배열의 깊이, 행, 열
print(len(array3)) #  깊이 
print(len(array3[0])) # 행
print(len(array3[0][0])) # 열

2
3
4


In [9]:
# 차원구하기 : .ndim 메소드
print(array3.ndim)

3


## numpy arrary를 만드는 다양한 방법
### 균일한 값으로 생성 : full 메소드

In [17]:
array1 = numpy.full(6,7) #(입력 횟수, 입력값)
array1

array([7, 7, 7, 7, 7, 7])

### 모든 값이 0인 numpy arrary생성

In [18]:
# full 메소드
array1 = numpy.full(6,0)
array1

array([0, 0, 0, 0, 0, 0])

**zeros 메소드**

In [20]:
array2 = numpy.zeros(6, dtype = int) #dtype defalut = float
array2

array([0, 0, 0, 0, 0, 0])

### 모든 값이 1인 numpy array 생성 : ones메소드

In [21]:
array1 = numpy.full(6,1)
array2 = numpy.ones(6, dtype = int)

In [22]:
print(array1)
print(array2)

[1 1 1 1 1 1]
[1 1 1 1 1 1]


### 랜덤한 값들로 생성 : random 모듈의 random함수

In [23]:
array1 = numpy.random.random(6)
array2 = numpy.random.random(6)

In [24]:
print(array1)
print(array2)

[0.34266987 0.32320517 0.94036269 0.52014486 0.82516969 0.34788913]
[0.59456315 0.41859713 0.54298848 0.26656568 0.44586297 0.3199636 ]


In [30]:
# 정수 random값 :random.randint(low, high,size=n)
array3 = numpy.random.randint(100, size=6)
array3

array([17, 87, 25, 74, 12, 73])

### 연속된 값들이 담긴 numpy array 생성 : arange함수
* 파라미터 1개 : arange(m) : 0 부터 m-1까지의 값들이 담긴 numpy array 리턴

In [25]:
array1 = numpy.arange(6)
array1

array([0, 1, 2, 3, 4, 5])

* 파라미터 2개 : arange(n,m) : n 부터 m-1까지 

In [26]:
array2 = numpy.arange(2,7)
array2

array([2, 3, 4, 5, 6])

* 파라미터 3개: arange(n,m,s) : n부터 m-1까지 간격s 인 값

In [27]:
array3 = numpy.arange(3,17,3)
array3

array([ 3,  6,  9, 12, 15])

## 모듈 별명 지어주기
모듈을 불러올 때 모둘명 전체를 사용하지 않고, 별명으로 보다 간단하게 사용할 수 있다.  
단, alias를 한번 지정해주면, 원 모듈명은 없는 값이 되어 사용이 불가하다.

In [31]:
import numpy as np

array1 = np.full(6,0)  # numpy.full이라고 쓰지 않고 np.full이라고 불러오기 가능
array2 = np.zeros(6)   

In [32]:
print(array1)
print(array2)

[0 0 0 0 0 0]
[0. 0. 0. 0. 0. 0.]


## numpy array 생성 연습 I
1부터 100까지(1과 100 포함) 담겨 있는 numpy array를 생성하고 출력해 주세요.

In [33]:
arr = np.arange(1,101)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

## numpy array 생성 연습 II
1 이상 100 이하의 자연수(수나 순서를 셀 때 쓰는 1, 2, 3 과 같은 수) 중 3의 배수만 담겨 있는 numpy array를 생성하고 출력해 주세요.

In [35]:
arr = np.arange(3,101, 3)
arr

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

## 인덱싱, 슬라이싱

* 위치 번호로 인덱싱 (파이썬 리스트와 동일) 

In [38]:
array1 = np.random.randint(2,31,size=11)
array1

array([ 2, 17, 24, 11, 28, 26, 13,  5,  7, 13, 17])

In [39]:
array1[2]

24

In [41]:
array1[0]

2

In [42]:
array1[-1]

17

In [44]:
array1[-3]

7

* List로 인덱싱 (인덱스를 리스트로 묶어서 한번에 가져오기) / 파이썬 리스트에서는 불가능

In [46]:
array1[[1, 3, 4]]

array([17, 11, 28])

In [55]:
#리스트에서는, 리스트로 인덱싱이 불가능하다. 
list1 = [2,3,4,5,6]
list1[[1,3,4]]

TypeError: list indices must be integers or slices, not list

In [49]:
# 리스트를 변수에 저장해서 그 변수로 호출할 수 도 있다.
array2 = np.array([2,1,3])
array1[array2]

array([24, 17, 11])

In [50]:
array1[2:7]

array([24, 11, 28, 26, 13])

In [51]:
array1[:7]

array([ 2, 17, 24, 11, 28, 26, 13])

In [52]:
array1[8:]

array([ 7, 13, 17])

In [53]:
# 슬라이싱에 step지정하기
array3 = np.arange(1,11)
array3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
array3[2:9:2] # 2번 이상, 9번 미만까지 1칸씩 건너뛰어서 출력

array([3, 5, 7, 9])

## numpy 기본연산

In [60]:
array1 = np.arange(10)
array2 = np.arange(10, 20)

In [57]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

* array 안의 값을 2배로 하고 싶다고 가정하면,  
  python list로 연산 시, for반복문을 사용해야 한다. 
  

In [59]:
for i in range(len(array1)) :
    array1[i] = 2 * array1[i]
array1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

* 수치계산 도구인 numpy 사용시에는 array간 직접 연산이 가능하다. 
* 벡터화 연산  
: 배열의 각 원소에 대한 반복 연산을 하나의 명령어로 처리하는 벡터화 연산을 지원한다. 

In [61]:
array1 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [62]:
array1 + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [63]:
array1 ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [64]:
# array 연산이 값을 저장하지는 않는다. 
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
array1 + array2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [66]:
array1 * array2

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

## 신주쿠 흥부부대찌개
실습과제
일본에는 한식 열풍이 불고 있습니다. 기회를 엿본 영훈이는 대기업을 퇴사하고 신주쿠에 프랜차이즈 ‘흥부부대찌개’ 가맹점을 냈습니다.

그러나 보수적인 아버지께서는 번듯한 직장을 박차고 나온 영훈이가 못마땅합니다. 아버지를 안심시켜 드리기 위해 매달 매출을 보고하려고 하는데요. 엔화(¥)로 저장한 매출 데이터를 원화(₩)로 변환하는 작업이 필요합니다.

마침 numpy를 배운 우리가 도와줄 수 있겠네요. 엔화 매출이 담겨 있는 파이썬 리스트가 주어졌습니다. 1엔에 10.08원이라고 가정하고, 원화 매출이 담긴 numpy array를 만들어 출력해 주세요.

반복문은 사용하면 안 됩니다!

In [67]:
revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

In [70]:
won_array = np.array(revenue_in_yen) * 10.08

In [71]:
won_array

array([3024000., 3427200., 3225600., 3628800., 4435200., 1411200.,
       1814400., 3427200., 3326400., 2923200., 2822400., 3830400.,
       1713600., 1411200., 2318400., 3931200., 4032000., 3528000.,
       3830400., 1512000., 1108800., 2419200., 3830400., 3830400.,
       3427200., 4233600., 1512000., 1310400., 3628800., 3225600.,
       2520000.])

## 흥부부대찌개 LA 진출
실습과제
흥부부대찌개 신주쿠점의 흥행에 성공한 영훈이는 여세를 몰아 LA에도 가맹점을 하나 냈습니다.

이제 아버지께 매출을 보고하기 위한 프로세스가 조금 복잡해졌습니다. 각 지점의 매출을 원화로 변환시키고 더해야 하죠. 1엔에 10.08원, 1달러에 1138원이라고 가정하세요. 그리고 두 지점의 매출의 합이 원화로 담긴 numpy array를 만들어 출력해주세요.

반복문은 사용하면 안 됩니다!

In [72]:
revenue_in_dollar = [
    1200, 1600, 1400, 1300, 
    2100, 1400, 1500, 2100, 
    1500, 1500, 2300, 2100, 
    2800, 2600, 1700, 1400, 
    2100, 2300, 1600, 1800, 
    2200, 2400, 2100, 2800, 
    1900, 2100, 1800, 2200, 
    2100, 1600, 1800
]

In [77]:
won_array = np.array(revenue_in_yen) * 10.08 + np.array(revenue_in_dollar) * 1138

In [78]:
won_array

array([4389600., 5248000., 4818800., 5108200., 6825000., 3004400.,
       3521400., 5817000., 5033400., 4630200., 5439800., 6220200.,
       4900000., 4370000., 4253000., 5524400., 6421800., 6145400.,
       5651200., 3560400., 3612400., 5150400., 6220200., 7016800.,
       5589400., 6623400., 3560400., 3814000., 6018600., 5046400.,
       4568400.])

## numpy 불린연산
불린연산도 array각 요소별로 한번에 할수 있다. 

In [80]:
array1 = np.array([2,3,5,7,11,13,17,19,23,31])

In [81]:
array1 > 4

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [82]:
array1 % 2 == 0

array([ True, False, False, False, False, False, False, False, False,
       False])

In [83]:
booleans = np.array([True, True, False, True, True, False, True, True, True, False, True, ])

In [84]:
np.where(booleans) # where = where condition is True 

(array([ 0,  1,  3,  4,  6,  7,  8, 10], dtype=int64),)

In [85]:
np.where(array1 > 4)

(array([2, 3, 4, 5, 6, 7, 8, 9], dtype=int64),)

In [86]:
filter = np.where(array1 > 4)
filter

(array([2, 3, 4, 5, 6, 7, 8, 9], dtype=int64),)

In [87]:
array1[filter] # array1 에서 4보다 큰 값들만 출력하는 결과를 가져온다. 

array([ 5,  7, 11, 13, 17, 19, 23, 31])

## 흥부부대찌개 목표 일 매출
실습과제  
영훈이가 창업한 흥부부대찌개 신주쿠점은 이제 직장인들에게 소문난 맛집입니다. 그러나 매일같이 성공적인 것은 아닙니다. 목표 일 매출을 달성하지 못하는 날들이 아직 꽤 있거든요. 영훈이가 생각하는 성공적인 하루 매출은 20만 엔입니다.

성공적이지 않은 날의 매출만 골라서 보고 싶습니다. 20만 엔 이하의 매출만 담긴 numpy array를 출력해주세요.
반복문은 사용하면 안 됩니다!

In [99]:
revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

In [100]:
array_in_yen = np.array(revenue_in_yen)
np.where(array_in_yen <= 200000)

(array([ 5,  6, 12, 13, 19, 20, 26, 27], dtype=int64),)

In [101]:
bad_days_revenue = array_in_yen[np.where(array_in_yen <= 200000)]
bad_days_revenue

array([140000, 180000, 170000, 140000, 150000, 110000, 150000, 130000])

In [102]:
# where없이 바로 인덱싱도 가능하다. 
array_in_yen[array_in_yen <= 200000]


array([140000, 180000, 170000, 140000, 150000, 110000, 150000, 130000])

## numpy 기본통계
### 최댓값, 최솟값 : max메소드, min 메소드

In [103]:
array1 = np.array([14, 6, 13, 21, 23, 31, 9, 5])
print(array1.max())
print(array1.min())

31
5


### 평균값: mean메소드

In [104]:
array1.mean()

15.25

### 중앙값 : median메소드 
* numpy array의 메소드가 아니라, numpy의 메소드이다. 

In [105]:
array1 = np.array([8, 12, 9, 15, 16])
array2 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

In [106]:
#numpy의 메소드 median
np.median(array1)

12.0

In [107]:
#numpy array의 메소드처럼 사용시 에러 
array1.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [108]:
np.median(array2)

13.5

### 표준편차, 분산 : std, var메소드

In [110]:
array1 = np.array([14, 6, 13, 21, 23, 31, 9, 5])
print(array1.std())
print(array1.var())

8.496322733983215
72.1875


# Pandas
데이터분석을 효율적으로 하기 위해 Data Frame 형태의 자료형을 다루는데 특화된 라이브러리

## DataFrame
표형식의 데이터를 담는 자료형
* column(열): 데이터의 특징
* row/index(행): 레코드
* row와 column에 이름을 붙혀 줄 수 있다. 

In [1]:
import pandas as pd 

### Data Frame 생성

In [11]:
two_dimensional_list = [['dongwook', 50, 86], ['sineui', 89, 31], ['ikjoong', 68, 91], ['yoonsoo', 88, 75]]

In [13]:
my_df = pd.DataFrame(two_dimensional_list, columns=['name','english_score', 'math_score'], index =['a','b','c','d'])
my_df

name  english_score  math_score
a  dongwook             50          86
b    sineui             89          31
c   ikjoong             68          91
d   yoonsoo             88          75

In [6]:
type(my_df)

pandas.core.frame.DataFrame

### 열 이름 출력

In [16]:
my_df.columns

Index(['name', 'english_score', 'math_score'], dtype='object')

### 행 이름 출력

In [17]:
my_df.index

Index(['a', 'b', 'c', 'd'], dtype='object')

### 각 컬럼 자료형 확인  
한 데이터 프레임 내에서 다양한 자료형을 담을 수 있지만, 같은 컬럼 안에서는 모두 같은 자료형을 입력해야 한다. 

In [18]:
my_df.dtypes

name             object
english_score     int64
math_score        int64
dtype: object

## DataFrame을 만드는 다양한 방법
### 2차원 리스트로 만들기

In [19]:
two_dimensional_list = [['dongwook', 50, 86], ['sineui', 89, 31], ['ikjoong', 68, 91], ['yoonsoo', 88, 75]]
df1 = pd.DataFrame(two_dimensional_list)
df1

0   1   2
0  dongwook  50  86
1    sineui  89  31
2   ikjoong  68  91
3   yoonsoo  88  75

### 2차원 numpy array로 만들기

In [21]:
import numpy as np

two_dimensional_array = np.array(two_dimensional_list)
df2 = pd.DataFrame(two_dimensional_array)
df2

0   1   2
0  dongwook  50  86
1    sineui  89  31
2   ikjoong  68  91
3   yoonsoo  88  75

###  pandas Series를 담고 있는 리스트로 만들기

In [23]:
#시리즈
pd.Series(['dongwook', 50, 86])

0    dongwook
1          50
2          86
dtype: object

In [24]:
list_of_series = [
    pd.Series(['dongwook', 50, 86]), 
    pd.Series(['sineui', 89, 31]), 
    pd.Series(['ikjoong', 68, 91]), 
    pd.Series(['yoonsoo', 88, 75])
]
list_of_series

[0    dongwook
 1          50
 2          86
 dtype: object,
 0    sineui
 1        89
 2        31
 dtype: object,
 0    ikjoong
 1         68
 2         91
 dtype: object,
 0    yoonsoo
 1         88
 2         75
 dtype: object]

In [25]:
df3 = pd.DataFrame(list_of_series)
df3

0   1   2
0  dongwook  50  86
1    sineui  89  31
2   ikjoong  68  91
3   yoonsoo  88  75

### Dictionary로 만들기 
* key = column  이름
* value -> 컬럼에 해당하는 값 (리스트, numpy array, 혹은 pandas Series 등의 형태로 입력 가능)

In [26]:
names = ['dongwook', 'sineui', 'ikjoong', 'yoonsoo']
english_scores = [50, 89, 68, 88]
math_scores = [86, 31, 91, 75]

In [27]:
#리스트로 사전만들기
dict1 = {
    'name': names,
    'english_score': english_scores,
    'math_score': math_scores
}
dict1

{'name': ['dongwook', 'sineui', 'ikjoong', 'yoonsoo'],
 'english_score': [50, 89, 68, 88],
 'math_score': [86, 31, 91, 75]}

In [35]:
#numpy array로 사전만들기
dict2 = {
    'name': np.array(names), 
    'english_score': np.array(english_scores), 
    'math_score': np.array(math_scores)
}
dict2

{'name': array(['dongwook', 'sineui', 'ikjoong', 'yoonsoo'], dtype='<U8'),
 'english_score': array([50, 89, 68, 88]),
 'math_score': array([86, 31, 91, 75])}

In [31]:
# Pandas Series로 사전만들기
dict3 = {
    'name': pd.Series(names), 
    'english_score': pd.Series(english_scores), 
    'math_score': pd.Series(math_scores)
}

In [32]:
# Dictionary로 DataFrame만들기
df1 = pd.DataFrame(dict1)
df2 = pd.DataFrame(dict2)
df3 = pd.DataFrame(dict3)

df1

name  english_score  math_score
0  dongwook             50          86
1    sineui             89          31
2   ikjoong             68          91
3   yoonsoo             88          75

In [34]:
# 어떤 방식으로 만든 사전을 활용하던 다 같은 데이터 프레임을 생성한다. 
df1 == df2

name  english_score  math_score
0  True           True        True
1  True           True        True
2  True           True        True
3  True           True        True

### 사전이 담긴 리스트로 만들기 

In [37]:
my_list = [
    {'name': 'dongwook', 'english_score': 50, 'math_score': 86},
    {'name': 'sineui', 'english_score': 89, 'math_score': 31},
    {'name': 'ikjoong', 'english_score': 68, 'math_score': 91},
    {'name': 'yoonsoo', 'english_score': 88, 'math_score': 75}
]

df = pd.DataFrame(my_list)
df

name  english_score  math_score
0  dongwook             50          86
1    sineui             89          31
2   ikjoong             68          91
3   yoonsoo             88          75

## [실습] 스타들의 생일은 언제?  

아래와 같은 결과가 나오도록 DataFrame을 만들고 출력해 보세요.  
column은 name, birthday, occupation 총 3개입니다.  

```
name	birthday	occupation
0	Taylor Swift	December 13, 1989	Singer-songwriter
1	Aaron Sorkin	June 9, 1961	Screenwriter
2	Harry Potter	July 31, 1980	Wizard
3	Ji-Sung Park	February 25, 1981	Footballer
```

### dictionary로 df 만들기

In [39]:
name = ['Taylor Swift','Aaron Sorkin','Harry Potter','Ji-Sung Park']
birthday = ['December 13, 1989','June 9, 1961','July 31, 1980','February 25, 1981']
occupation = ['Singer-songwriter', 'Screenwriter', 'Wizard', 'Footballer']

In [40]:
dict_stars = {
    'name': name,
    'birthday' : birthday,
    'occupation' : occupation
}
df = pd.DataFrame(dict_stars)
df

name           birthday         occupation
0  Taylor Swift  December 13, 1989  Singer-songwriter
1  Aaron Sorkin       June 9, 1961       Screenwriter
2  Harry Potter      July 31, 1980             Wizard
3  Ji-Sung Park  February 25, 1981         Footballer

### list로 df만들기

In [41]:
 stars = [
     ['Taylor Swift', 'December 13, 1989', 'Singer-songwriter'],
     ['Aaron Sorkin', 'June 9, 1961', 'Screenwriter'],
     ['Harry Potter', 'July 31, 1980', 'Wizard'],
     ['Ji-Sung Park', 'February 25, 1981', 'Footballer']
 ]
df = pd.DataFrame(stars, columns= ['name', 'birthday', 'occupation'])
df                                   

name           birthday         occupation
0  Taylor Swift  December 13, 1989  Singer-songwriter
1  Aaron Sorkin       June 9, 1961       Screenwriter
2  Harry Potter      July 31, 1980             Wizard
3  Ji-Sung Park  February 25, 1981         Footballer