# Numpy
## Numpy란?
### numerical python 

파이썬에서 복잡한 수치계산도 효율적으로 동작 가능하도록 만든 프로그램
대용량의 수치 데이터를 Numpy array 형태로 간편하고 효율적으로 저장하고 사용할 수 있음.

## numpy array의 생김새 


In [1]:
import numpy

In [2]:
array1 = numpy.array([2,3,4,7,11,13,17,19,23,29,31])
    # numpy 모듈의 array함수에 파이썬 리스트를 파라미터로 사용하여 numpy array를 만듬

In [3]:
array1

array([ 2,  3,  4,  7, 11, 13, 17, 19, 23, 29, 31])

**ndarray**  
n dimensional array. n차원의 배열. array는 다차원으로 배열을 만들 수 있다. 

* numpy arrary의 차원

In [4]:
type(array1)

numpy.ndarray

* 1차원

In [5]:
array1.shape

(11,)

* 2차원

In [8]:
array2 = numpy.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [9]:
type(array2)

numpy.ndarray

In [11]:
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

array안에 array가 있는 2차원 배열이다.  
shape 출력 시 세로 가로 길이가 나온다. 

In [10]:
array2.shape

(3, 4)

* 3차원

In [12]:
array3 = numpy.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [13]:
array3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [15]:
array3.shape

(2, 2, 2)

## numpy arrary를 만드는 다양한 방법
### 균일한 값으로 생성 : full 메소드

In [17]:
array1 = numpy.full(6,7) #(입력 횟수, 입력값)
array1

array([7, 7, 7, 7, 7, 7])

### 모든 값이 0인 numpy arrary생성

In [18]:
# full 메소드
array1 = numpy.full(6,0)
array1

array([0, 0, 0, 0, 0, 0])

**zeros 메소드**

In [20]:
array2 = numpy.zeros(6, dtype = int) #dtype defalut = float
array2

array([0, 0, 0, 0, 0, 0])

### 모든 값이 1인 numpy array 생성 : ones메소드

In [21]:
array1 = numpy.full(6,1)
array2 = numpy.ones(6, dtype = int)

In [22]:
print(array1)
print(array2)

[1 1 1 1 1 1]
[1 1 1 1 1 1]


### 랜덤한 값들로 생성 : random 모듈의 random함수

In [23]:
array1 = numpy.random.random(6)
array2 = numpy.random.random(6)

In [24]:
print(array1)
print(array2)

[0.34266987 0.32320517 0.94036269 0.52014486 0.82516969 0.34788913]
[0.59456315 0.41859713 0.54298848 0.26656568 0.44586297 0.3199636 ]
